version: "2"

services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_DATABASE: "smart_examination"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "P@ssw0rd"
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
    networks:
      - smart-examination-network
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d
    command: >
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --connect_timeout=31536000
      --wait_timeout=31536000
      --max_allowed_packet=67108864
volumes:
  my-db:
  portainer_data:
  video_storage:

networks:
  smart-examination-network:
    external: true

  # portainer_agent:
  #   image: portainer/agent
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/volumes:/var/lib/docker/volumes
  #   ports:
  #     - "9001:9001"
  #   networks:
  #     - smart-examination-network

  # portainer:
  #   container_name: portainer
  #   restart: always
  #   image: portainer/portainer
  #   volumes:
  #     - portainer_data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - smart-examination-network
  #   ports:
  #     - "9000:9000"
  #   expose:
  #     - "9000"

  # server:
  #   container_name: smart-examination-backend
  #   image: "phuicmt/smart-examination-backend"
  #   restart: always
  #   networks:
  #     - smart-examination-network
  #   ports:
  #     - "5000:5000"
  #   expose:
  #     - "5000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - video_storage:/server/app/video_storage

  # web:
  #   container_name: smart-examination-fontend
  #   image: "phuicmt/smart-examination-fontend"
  #   restart: always
  #   networks:
  #     - smart-examination-network
  #   ports:
  #     - "3000:3000"
  #   expose:
  #     - "3000"
  #   depends_on:
  #     - server
  #     - db
  #   environment:
  #     DANGEROUSLY_DISABLE_HOST_CHECK: "true"

  # rabbitmq-reader:
  #   container_name: phq-9-rabbitmq
  #   image: "phuicmt/phq-9-rabbitmq"
  #   restart: always
  #   networks:
  #     - smart-examination-network
  #   ports:
  #     - "5002:5002"
  #   depends_on:
  #     - server
  #     - db
  #     - web
  #     - rabbitmq

  # rabbitmq:
  #   image: rabbitmq:3.8-management-alpine
  #   container_name: "rabbitmq"
  #   restart: always
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=admin
  #   ports:
  #     - 15672:15672
  #     - 15671:15671
  #     - 5672:5672
  #   expose:
  #     - "15672"
  #     - "5672"
  #   networks:
  #     - smart-examination-network
